version: 2

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    environment:
      TERM: dumb

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "kotlinjs/build.gradle.kts" }}
            - v1-dependencies-

      - run: cd kotlinjs && ./gradlew build ; cd ..
      - run: npm install
      - run: git add . && commit -m "Update generated files" && git push origin || echo "Didn't update any generated files"

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "kotlinjs/build.gradle.kts" }}
